export const searchableItems = [
  { label: "Bag", value: "_BAG" },
  { label: "Cape", value: "_CAPE" },
  { label: "Scholar Robe", value: "_ARMOR_CLOTH_SET1" },
  { label: "Cleric Robe", value: "_ARMOR_CLOTH_SET2" },
  { label: "Mage Robe", value: "_ARMOR_CLOTH_SET3" },
  { label: "Druid Robe", value: "_ARMOR_CLOTH_KEEPER" },
  { label: "Fiend Robe", value: "_ARMOR_CLOTH_HELL" },
  { label: "Cultist Robe", value: "_ARMOR_CLOTH_MORGANA" },
  { label: "Scholar Cowl", value: "_HEAD_CLOTH_SET1" },
  { label: "Cleric Cowl", value: "_HEAD_CLOTH_SET2" },
  { label: "Mage Cowl", value: "_HEAD_CLOTH_SET3" },
  { label: "Druid Cowl", value: "_HEAD_CLOTH_KEEPER" },
  { label: "Fiend Cowl", value: "_HEAD_CLOTH_HELL" },
  { label: "Cultist Cowl", value: "_HEAD_CLOTH_MORGANA" },
  { label: "Scholar Sandals", value: "_SHOES_CLOTH_SET1" },
  { label: "Cleric Sandals", value: "_SHOES_CLOTH_SET2" },
  { label: "Mage Sandals", value: "_SHOES_CLOTH_SET3" },
  { label: "Druid Sandals", value: "_SHOES_CLOTH_KEEPER" },
  { label: "Fiend Sandals", value: "_SHOES_CLOTH_HELL" },
  { label: "Cultist Sandals", value: "_SHOES_CLOTH_MORGANA" },
  { label: "Mercenary Jacket", value: "_ARMOR_LEATHER_SET1" },
  { label: "Hunter Jacket", value: "_ARMOR_LEATHER_SET2" },
  { label: "Assassin Jacket", value: "_ARMOR_LEATHER_SET3" },
  { label: "Stalker Jacket", value: "_ARMOR_LEATHER_MORGANA" },
  { label: "Hellion Jacket", value: "_ARMOR_LEATHER_HELL" },
  { label: "Specter Jacket", value: "_ARMOR_LEATHER_UNDEAD" },
  { label: "Mercenary Hood", value: "_HEAD_LEATHER_SET1" },
  { label: "Hunter Hood", value: "_HEAD_LEATHER_SET2" },
  { label: "Assassin Hood", value: "_HEAD_LEATHER_SET3" },
  { label: "Stalker Hood", value: "_HEAD_LEATHER_MORGANA" },
  { label: "Hellion Hood", value: "_HEAD_LEATHER_HELL" },
  { label: "Specter Hood", value: "_HEAD_LEATHER_UNDEAD" },
  { label: "Mercenary Shoes", value: "_SHOES_LEATHER_SET1" },
  { label: "Hunter Shoes", value: "_SHOES_LEATHER_SET2" },
  { label: "Assassin Shoes", value: "_SHOES_LEATHER_SET3" },
  { label: "Stalker Shoes", value: "_SHOES_LEATHER_MORGANA" },
  { label: "Hellion Shoes", value: "_SHOES_LEATHER_HELL" },
  { label: "Specter Shoes", value: "_SHOES_LEATHER_UNDEAD" },
  { label: "Soldier Armor", value: "_ARMOR_PLATE_SET1" },
  { label: "Knight Armor", value: "_ARMOR_PLATE_SET2" },
  { label: "Guardian Armor", value: "_ARMOR_PLATE_SET3" },
  { label: "Graveguard Armor", value: "_ARMOR_PLATE_UNDEAD" },
  { label: "Demon Armor", value: "_ARMOR_PLATE_HELL" },
  { label: "Judicator Armor", value: "_ARMOR_PLATE_KEEPER" },
  { label: "Soldier Helmet", value: "_HEAD_PLATE_SET1" },
  { label: "Knight Helmet", value: "_HEAD_PLATE_SET2" },
  { label: "Guardian Helmet", value: "_HEAD_PLATE_SET3" },
  { label: "Graveguard Helmet", value: "_HEAD_PLATE_UNDEAD" },
  { label: "Demon Helmet", value: "_HEAD_PLATE_HELL" },
  { label: "Judicator Helmet", value: "_HEAD_PLATE_KEEPER" },
  { label: "Soldier Boots", value: "_SHOES_PLATE_SET1" },
  { label: "Knight Boots", value: "_SHOES_PLATE_SET2" },
  { label: "Guardian Boots", value: "_SHOES_PLATE_SET3" },
  { label: "Graveguard Boots", value: "_SHOES_PLATE_UNDEAD" },
  { label: "Demon Boots", value: "_SHOES_PLATE_HELL" },
  { label: "Judicator Boots", value: "_SHOES_PLATE_KEEPER" },
  { label: "Arcane Staff", value: "_MAIN_ARCANESTAFF" },
  { label: "Great Arcane Staff", value: "_2H_ARCANESTAFF" },
  { label: "Enigmatic Staff", value: "_2H_ENIGMATICSTAFF" },
  { label: "Witchwork Staff", value: "_MAIN_ARCANESTAFF_UNDEAD" },
  { label: "Occult Staff", value: "_2H_ARCANESTAFF_HELL" },
  { label: "Malevolent Locus", value: "_2H_ENIGMATICORB_MORGANA" },
  { label: "Cursed Staff", value: "_MAIN_CURSEDSTAFF" },
  { label: "Great Cursed Staff", value: "_2H_CURSEDSTAFF" },
  { label: "Demonic Staff", value: "_2H_DEMONICSTAFF" },
  { label: "Lifecurse Staff", value: "_MAIN_CURSEDSTAFF_UNDEAD" },
  { label: "Cursed Skull", value: "_2H_SKULLORB_HELL" },
  { label: "Damnation Staff", value: "_2H_CURSEDSTAFF_MORGANA" },
  { label: "Fire Staff", value: "_MAIN_FIRESTAFF" },
  { label: "Great Fire Staff", value: "_2H_FIRESTAFF" },
  { label: "Infernal Staff", value: "_2H_INFERNOSTAFF" },
  { label: "Wildfire Staff", value: "_MAIN_FIRESTAFF_KEEPER" },
  { label: "Brimstone Staff", value: "_2H_FIRESTAFF_HELL" },
  { label: "Blazing Staff", value: "_2H_INFERNOSTAFF_MORGANA" },
  { label: "Frost Staff", value: "_MAIN_FROSTSTAFF" },
  { label: "Great Frost Staff", value: "_2H_FROSTSTAFF" },
  { label: "Glacial Staff", value: "_2H_GLACIALSTAFF" },
  { label: "Hoarfrost Staff", value: "_MAIN_FROSTSTAFF_KEEPER" },
  { label: "Icicle Staff", value: "_2H_ICEGAUNTLETS_HELL" },
  { label: "Permafrost Staff", value: "_2H_ICECRYSTAL_UNDEAD" },
  { label: "Holy Staff", value: "_MAIN_HOLYSTAFF" },
  { label: "Great Holy Staff", value: "_2H_HOLYSTAFF" },
  { label: "Divine Staff", value: "_2H_DIVINESTAFF" },
  { label: "Lifetouch Staff", value: "_MAIN_HOLYSTAFF_MORGANA" },
  { label: "Fallen Staff", value: "_2H_HOLYSTAFF_HELL" },
  { label: "Redemption Staff", value: "_2H_HOLYSTAFF_UNDEAD" },
  { label: "Nature Staff", value: "_MAIN_NATURESTAFF" },
  { label: "Great Nature Staff", value: "_2H_NATURESTAFF" },
  { label: "Wild Staff", value: "_2H_WILDSTAFF" },
  { label: "Druidic Staff", value: "_MAIN_NATURESTAFF_KEEPER" },
  { label: "Blight Staff", value: "_2H_NATURESTAFF_HELL" },
  { label: "Rampant Staff", value: "_2H_NATURESTAFF_KEEPER" },
  { label: "Battleaxe", value: "_MAIN_AXE" },
  { label: "Greataxe ", value: "_2H_AXE" },
  { label: "Halberd", value: "_2H_HALBERD" },
  { label: "Carrioncaller", value: "_2H_HALBERD_MORGANA" },
  { label: "Infernal Scythe", value: "_2H_SCYTHE_HELL" },
  { label: "Bear Paws", value: "_2H_DUALAXE_KEEPER" },
  { label: "Dagger", value: "_MAIN_DAGGER" },
  { label: "Dagger Pair", value: "_2H_DAGGERPAIR" },
  { label: "Claws", value: "_2H_CLAWPAIR" },
  { label: "Bloodletter", value: "_MAIN_RAPIER_MORGANA" },
  { label: "Black Hands", value: "_2H_IRONGAUNTLETS_HELL" },
  { label: "Deathgivers", value: "_2H_DUALSICKLE_UNDEAD" },
  { label: "Hammer", value: "_MAIN_HAMMER" },
  { label: "Great Hammer", value: "_2H_HAMMER" },
  { label: "Polehammer", value: "_2H_POLEHAMMER" },
  { label: "Tombhammer", value: "_2H_HAMMER_UNDEAD" },
  { label: "Forge Hammers", value: "_2H_DUALHAMMER_HELL" },
  { label: "Grovekeeper", value: "_2H_RAM_KEEPER" },
  { label: "Mace", value: "_MAIN_MACE" },
  { label: "Heavy Mace", value: "_2H_MACE" },
  { label: "Morning Star", value: "_2H_FLAIL" },
  { label: "Bedrock Mace", value: "_MAIN_ROCKMACE_KEEPER" },
  { label: "Incubus Mace", value: "_MAIN_MACE_HELL" },
  { label: "Camlann Mace", value: "_2H_MACE_MORGANA" },
  { label: "Quarterstaff", value: "_2H_QUARTERSTAFF" },
  { label: "Iron-Clad Staff", value: "_2H_IRONCLADEDSTAFF" },
  { label: "Double Bladed Staff", value: "_2H_DOUBLEBLADEDSTAFF" },
  { label: "Black Monk Staff", value: "_2H_COMBATSTAFF_MORGANA" },
  { label: "Soulscythe", value: "_2H_TWINSCYTHE_HELL" },
  { label: "Staff of Balance", value: "_2H_ROCKSTAFF_KEEPER" },
  { label: "Spear", value: "_MAIN_SPEAR" },
  { label: "Glaive", value: "_2H_GLAIVE" },
  { label: "Pike", value: "_2H_SPEAR" },
  { label: "Heron Spear", value: "_MAIN_SPEAR_KEEPER" },
  { label: "Spirithunter", value: "_2H_HARPOON_HELL" },
  { label: "Trinity Spear", value: "_2H_TRIDENT_UNDEAD" },
  { label: "Broadsword", value: "_MAIN_SWORD" },
  { label: "Dual Swords", value: "_2H_DUALSWORD" },
  { label: "Claymore", value: "_2H_CLAYMORE" },
  { label: "Clarent Blade", value: "_MAIN_SCIMITAR_MORGANA" },
  { label: "Carving Sword", value: "_2H_CLEAVER_HELL" },
  { label: "Galatine Pair", value: "_2H_DUALSCIMITAR_UNDEAD" },
  { label: "Tome of Spells", value: "_OFF_BOOK" },
  { label: "Muisak", value: "_OFF_DEMONSKULL_HELL" },
  { label: "Mistcaller", value: "_OFF_HORN_KEEPER" },
  { label: "Eye of Secrets", value: "_OFF_ORB_MORGANA" },
  { label: "Shield", value: "_OFF_SHIELD" },
  { label: "Sarcophagus", value: "_OFF_TOWERSHIELD_UNDEAD" },
  { label: "Caitiff Shield", value: "_OFF_SHIELD_HELL" },
  { label: "Facebreaker", value: "_OFF_SPIKEDSHIELD_MORGANA" },
  { label: "Torch", value: "_OFF_TORCH" },
  { label: "Leering Cane", value: "_OFF_JESTERCANE_HELL" },
  { label: "Cryptcandle", value: "_OFF_LAMP_UNDEAD" },
  { label: "Taproot", value: "_OFF_TOTEM_KEEPER" },
  { label: "Bow", value: "_2H_BOW" },
  { label: "Longbow", value: "_2H_LONGBOW" },
  { label: "Warbow", value: "_2H_WARBOW" },
  { label: "Whispering Bow", value: "_2H_LONGBOW_UNDEAD" },
  { label: "Wailing Bow", value: "_2H_BOW_HELL" },
  { label: "Bow of Badon", value: "_2H_BOW_KEEPER" },
  { label: "Crossbow", value: "_2H_CROSSBOW" },
  { label: "Heavy Crossbow", value: "_2H_CROSSBOWLARGE" },
  { label: "Light Crossbow", value: "_MAIN_1HCROSSBOW" },
  { label: "Weeping Repeater", value: "_2H_REPEATINGCROSSBOW_UNDEAD" },
  { label: "Boltcasters", value: "_2H_DUALCROSSBOW_HELL" },
  { label: "Siegebow", value: "_2H_CROSSBOWLARGE_MORGANA" },
];
